### ISSUE TITLE
MetFrag CL, Could not open URL connection 

### ISSUE THREAD

**Issue by gjgetzinger** [c-ruttkies/MetFragRelaunched#6]
MetFrag2.2-CL can not connect to PubChem to retrieve candidates (works without issue when using a local sdf file as input). 

# with PubChem search 
```{bash}
$ java -jar /dscrhome/pf31/apps/MetFrag_2.2CL/MetFrag2.2-CL.jar /dscrhome/gjg3/data/test/MetFragParam_web.txt
INFO  de.ipbhalle.metfraglib.database.OnlinePubChemDatabase - Fetching candidates from PubChem
Error: Could not open URL connection!
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pccompound&term=314.0927238365284[MIMass]:314.0958647794715[MIMass]&retmode=json&retmax=100000
java.lang.Exception
	at de.ipbhalle.metfraglib.functions.HelperFunctions.getInputStreamFromURL(HelperFunctions.java:66)
	at de.ipbhalle.metfraglib.database.OnlinePubChemDatabase.getCandidateIdentifiers(OnlinePubChemDatabase.java:78)
	at de.ipbhalle.metfraglib.database.OnlinePubChemDatabase.getCandidateIdentifiers(OnlinePubChemDatabase.java:59)
	at de.ipbhalle.metfraglib.process.CombinedMetFragProcess.retrieveCompounds(CombinedMetFragProcess.java:61)
	at de.ipbhalle.metfrag.commandline.CommandLineTool.main(CommandLineTool.java:72)
ERROR de.ipbhalle.metfrag.commandline.CommandLineTool - Error when retrieving compounds.

 ~/data/test $ more MetFragParam_web.txt 
PeakListPath = test_ms2.txt
MetFragDatabaseType = PubChem
NeutralPrecursorMass = 314.094294308
FragmentPeakMatchAbsoluteMassDeviation = 0.005
FragmentPeakMatchRelativeMassDeviation = 5
DatabaseSearchRelativeMassDeviation = 5
PrecursorIonMode = 1
IsPositiveIonMode = True
MetFragScoreTypes = FragmenterScore
MetFragScoreWeights = 1.0
MetFragCandidateWriter = SDF
SampleName = metfrag_out
ResultsPath = /dscrhome/gjg3/data/test/
MaximumTreeDepth = 2
NumberThreads = 1

```
# using same parameter file except with local sdf as mol input
```{bash}
~/data/test $ java -jar /dscrhome/pf31/apps/MetFrag_2.2CL/MetFrag2.2-CL.jar /dscrhome/gjg3/data/test/MetFragParam.txt
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - Got 201 candidate(s)
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 10 %
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 20 %
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 30 %
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 40 %
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 50 %
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 60 %
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 70 %
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 80 %
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 90 %
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 100 %
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 0 candidate(s) were discarded before processing due to pre-filtering
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 0 candidate(s) discarded during processing due to errors
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 0 candidate(s) discarded after processing due to post-filtering
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - Stored 201 candidate(s)

$ more MetFragParam.txt 
PeakListPath = test_ms2.txt
MetFragDatabaseType = LocalSDF
LocalDatabasePath = /dscrhome/gjg3/data/EvalData//AABUKWVVUWBZCS-UHFFFAOYSA-N/magma_out.sdf
NeutralPrecursorMass = 314.094294308
FragmentPeakMatchAbsoluteMassDeviation = 0.005
FragmentPeakMatchRelativeMassDeviation = 5
DatabaseSearchRelativeMassDeviation = 5
PrecursorIonMode = 1
IsPositiveIonMode = True
MetFragScoreTypes = FragmenterScore
MetFragScoreWeights = 1.0
MetFragCandidateWriter = SDF
SampleName = metfrag_out
ResultsPath = /dscrhome/gjg3/data/test/
MaximumTreeDepth = 2
NumberThreads = 1

```
# system info
```{bash}
$ uname -a
Linux dscr-slogin-02 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Oct 26 10:25:23 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by c-ruttkies** [comment]
Hi Gordon,

could you download the latest version of MetFrag (2.3) from http://msbi.ipb-halle.de/~cruttkie/metfrag/MetFrag2.3-CL.jar ?

The online PubChem service recently has stopped maintaining their REST service over http. This has been fixed in version 2.3.

Best regards,
Christoph

**Comment by JB-MS** [comment]
@c-ruttkies 

Unfortunately, the link does not work:

> You don't have permission to access /~cruttkie/metfrag/MetFrag2.3-CL.jar on this server.

Also, i was not able to compile the tool via mvn on macOS Sierra.

Is there another place, where i can download the .jar?

Cheers,
Johannes

**Comment by c-ruttkies** [comment]
Hi Johannes,

thanks for posting this issue. Should be working now.

Best regards,
Christoph

**Comment by JB-MS** [comment]
Hi Christoph,

thanks! The download link works now.

I will test is asap and let you know if everything works.

Cheers,
Johannes
